### ISSUE TITLE
Subpath imports misidentified as external imports

### ISSUE THREAD

**Issue by olets** [unjs/unbuild#467] opened 2024-12-27 14:10 UTC
### Environment

- unbuild v3.0.1
- Node v18.20.3

### Reproduction

https://stackblitz.com/edit/unbuild-301-subpath-import-false-positive-warning

### Describe the bug

Using package.json subpath imports https://nodejs.org/api/packages.html#subpath-imports without `failOnWarn: false` gives an error.

### Additional context

- This is the 3.x version of my 2.x report in https://github.com/unjs/unbuild/issues/201#issuecomment-2349892637

### Logs

```sh
WARN  Build is done with some warnings:

- Inlined implicit external #x.ts
```

**Comment by pi0** [comment] 2024-12-27 14:11
Thanks for reproduction. It is same as #351 I guess

**Comment by olets** [comment] 2024-12-27 14:15
Thanks yeah was about to comment that it could be related to #351. Didn't know what the motivation for 351 was, and I don't know the system well enough to comment on whether adding subpaths to externals is the best solution.

**Comment by pi0** [comment] 2024-12-27 14:17
np thanks for confirm. let's track it from there then (closing since currently doing a triage to reduce open issues)

**Closed by pi0** 2024-12-27 14:17 UTC
Labels: bug
